### PR TITLE
Create calculator_js.html

### PR DESCRIPTION
**Pull request by RAJEEVGUPTA950**

### CODE REVIEW

**Comment by Hariom8799** [comment]
Bro can you pls explain what you did in this

**Comment by Hariom8799** [comment]
Also send ss of that

**Comment by RAJEEVGUPTA950** [comment]
sorry sir some part was missing.

**Comment by RAJEEVGUPTA950** [comment]
now its fine

**Comment by Hariom8799** [comment]
Okkh pls send the screenshots of changes you made in ui

**Comment by RAJEEVGUPTA950** [comment]
now upload a pic ..see please.

**Pull request merged**
